import random

from flask import Flask

QUOTES = [
    """Playing with items on is anti-competitive. Turn them off and assert your superiority over anyone who disagrees.""",
    """You must defeet Uncle Sensei to stand a chance.""",
    """Having trouble with an opponent who blocks too much? Try using a throw.""",
    """If you lose power, consider plugging the game into an outlet in the bathroom to continue playing.""",
    """We have a kill screen coming up!""",
    """No balcony? No problem!""",
    """If the game won't load, try blowing into the bottom of the cartridge.""",
    """Food: Chicken""",
    """Having trouble winning? Attend DeVon's "Going Hard" seminar at 11PM TST (Tournament Standard Time).""",
    """No hot water? Double down on some deodorant.""",
    """Winners don't pet pugs.""",
    """When playing online, be sure to pull the plug just before a loss to keep a perfect record.""",
    """You can lead a horse-head to water...""",
    """If you get hit with the echo sound waves, your controls become "Dolphiny" and the game will only check them every 8 frames.""",
    """Some cars are faster than others, so be sure you have the right ride for each job.""",
    """Input delay offline is often caused by image post-processing.""",
    """When playing on an obviously laggy monitor, saying that it doesn't bother you doesn't make you cool.""",
    """No one can beat the fabulous four.""",
    """If you are feeling pressured, mash out a DP to escape that nasty situation.""",
    """Try developing tight option selects to limit your opponent's escape options after a knockdown.""",
    """Pause during gameplay to disrupt your opponent's timing and view the in-game move list.""",
    """When facing a tough opponent, choose a character that is banned from tournament play for optimal results.""",
    """I used to be a bodybuilder, so I had to break up with my girlfriend.""",
    """How do you like my hat?!""",
    """The early bird may catch the worm, but the second mouse gets the cheese.""",
    """IFD brand clothes will make you stronger, or at least drunkerer.""",
    """Try a bag of Trusty Humbag's Meat-Flavored Taste-icles, now with bonus meat!""",
    """Shoot outside the screen to reload.""",
    """If you are spotted, remain in the shadows for a few moments to regain stealth mode.""",
    """There is somebody behind you.""",
    """I'm leaving you for Flying V.""",
    """Caution: Will cause cancer.""",
    """Over the age of 40? Check your prostate yearly.""",
    """If you meet a girl, don't ask her if she wants to see your arcade stick.""",
    """Don't pass out in the commentary area.""",
    """The more you mash, the worse the rash.""",
    """Don't leave your oversized jug of milk in the director's pit.""",
    """Anger is only one letter away from Danger.""",
    """Buy my product.""",
    """Wins only count if you finish with a super.""",
    """In order to fire the cannon, you must be holding the accelerator.""",
    """Passing control may seem inexpensive and safe, but winning without control is very difficult.""",
    """Wow wow wow wow wow wow wow wow wow.""",
    """It is 2013. Please stop driving around without a GPS.""",
    """Hold UP while selecting your character to play as a nude version.""",
    """The best character in the game is wearing a trenchcoat.""",
    """Follow @TheKeits and @DiveKickGame for updates about the Divekick world.""",
    """Do not play underwater.""",
    """The ultimate attack has a combination involving 12 buttons. You got the special edition controller, right?""",
    """Every match you play is a tutorial.""",
    """Help me.""",
    """In the real world, people use money to buy things.""",
    """Florida is not part of the East Coast.""",
    """Remember to drink lots of heavily caffeinated, intensely sweet soft drinks -- because you're an athlete.""",
    """Every time a top player borrows a stick, a kitten loses an eye.""",
    """The ultimate goal in life is to not end up in a GIF.""",
    """Who is doing this to me?""",
    """Hell hath no fury like a fanboy mildly inconvenienced.""",
    """The most important parts of a fighting game tournament are the chicken and strippers.""",
    """Hey I just got bodied, and this is shady, but good job winning, I'll pay you maybe.""",
    """N'est ce pas une tip.""",
    """The secret to a successful online business is custom emoticons.""",
    """Remember to act surprised when you're told wireless controllers are banned.""",
    """Make friends with top players -> Get carried to team tournament wins -> Profit!""",
    """We reserve the right to change payout dates and amounts without notice at any time.""",
    """Eat at Klembo's Jewish Kitchen. It's 100% kosher, 50% of the time!""",
    """Buy the extreme value bucket at Klembo's Jewish Kitchen and get a free Thug Life t-shirt.""",
    """Did you know that you can convert any bag of potato chips into "Breakfast Chips" by simply eating them for breakfast? #themoreyouknow""",
    """It's very likely that you've used the term Metagame in an attempt to sound smart, but you've accomplished the opposite by misusing it. Just stop.""",
    """Never turn down the gauntlet.""",
    """My distant cousin is a Nigerian Prince and left me a large sum! All I have to do is send him all of my personal and banking information to collect!""",
    """If you lose your password, you can reset it by following this email link.""",
    """If at first you don't succeed, make up excuses for why the loss doesn't count.""",
    """Hope is the first step on the road to disappointment.""",
    """You can pick your friends and you can pick you nose, and you can pick your friends' nose if they are sleeping.""",
    """Each creature has an attack type it is weak to. Test all of your moves to find out what works best.""",
    """It's super effective.""",
    """Make sure to play rock paper scissor for the player 1 spot, otherwise it's not fair.""",
    """Don't get caught in the snuggle vortex.""",
    """Using "borrowed" art and music makes video game creation easy AND fun!""",
    """Tweet more to feel more important.""",
    """Hugs are great from people you like, but if someone touches you in a way that makes you feel uncomfortable then that's NO GOOD.""",
    """Stay out of the woods when they are on fire.""",
    """Beware of strange men with mice.""",
    """Take the win if your opponent's controller disconnects in the middle of a match. You'll be glad you did.""",
    """My political alignment? Green party, I guess?""",
    """What if you could hate the player AND the game?""",
    """No matter how friendly it may sound, never accept a Winnipeg Handshake.""",
    """Reforming evil can be tricky.""",
    """Gimme this Abdominal Stretch!""",
    """Talk to everyone.""",
    """Join the One True Game Fun Club today, Mac!""",
    """Before avenging your father's death, leave some milk out for a kitten.""",
    """What can you tell me about the four Wu Du?""",
    """Would you like to play a game of lucky hit?""",
    """How about trying lucky hit?""",
    """Paying bills on a monthly basis will improve your credit.""",
    """Unless you break your controller, a loss costs only your price of entry and perhaps your pride.""",
    """Skunkbear.""",
    """The stairs to this place just lead off a cliff.""",
    """Spacingisimportantespeciallybetweenwordsinsentences.""",
    """E.D.F.!!! E.D.F.!!!""",
    """This game is played with your feet! When the arrow hits the top of the screen, step on the platform!""",
    """Don't look at me!""",
    """That's why I don't go outside.""",
    """Look before you leap.""",
    """Rub the green monster candy dispenser for good luck!""",
    """Always bring your own roll of toilet paper.""",
    """I once saw two deaf people get into an argument, it was the most awkward thing I've never heard.""",
    """If you can avoid it, don't have kids. It's just not worth it, no matter what your friends with kids say.""",
    """The longest road is the path to enlightenment. It does not surround the 2.""",
    """Release the next batch... of tips.""",
    """Just say "Ronaldo" out loud, and he is sure to drop his combo.""",
    """Odd that the winner of yet another raffle is an account with a signup date of three minutes ago.""",
    """Choose the joystick gate that suits you, unless it's a circle gate. Those are for squares.""",
    """Pay careful attention to the top screen to rack up fusion stars! Use these to activate a super-powerful fusion attack!""",
    """Consider the codes of your chips. This makes it possible to pull off powerful combos!""",
    """Everyone knows that City Trial is the best mode in the game.""",
    """At the end of the game, we will award stars to random players to make you even more angry than you already are.""",
    """Ordering a pizza with more than 3 toppings is a waste of money.""",
    """Cougars are also known as Pumas, Mountain cats, Mountain Lions, Mountain Screamers, Catamounts, Painters or Panthers and sometimes even older women on the prowl.""",
    """You're 10 times more likely to be bitten by a human than a rat.""",
    """Arrive at your pool on time.""",
    """Free, fraud, or fray can be used to replace any part of a persons name. Go on, try it!""",
    """It all depends on your skill! And character match-up, and stage selection, and latency, and your controller, and if your opponent insults you or not, pansy.""",
    """Barbecue sauce on rice is a TERRIBLE idea.""",
    """Don't dig down.""",
    """Join the One True Game Studios Fun Club today!""",
    """If you see an old lady crossing the street, let her go. Observe her. Learn from her mistakes so that you may succeed.""",
    """Last night I played a blank tape at full blast. The mime next door went nuts.""",
    """Always listen to your mother.... she might quiz you about it later!""",
    """Manic or Depressive. Choose your destiny.""",
    """It's always darkest before you pay the electrical bill.""",
    """The sole of a warrior is not to be tread on.""",
    """Scientifically speaking, we can't prove wearing silly hats DOESN'T heighten your fighting skills.""",
    """Please keep all organs inside your person.""",
    """Do not confuse fraudulent with flatulent.""",
    """They say only legends can become holograms...""",
    """12 people propagating lies over each other is not a "podcast".""",
    """Connecting to your opponent....""",
    """Visit the ocean. Experience the saltiness the Earth has for you.""",
    """Under Renovation -- Come back soon for a new and improved Uncle Sensei experience!""",
    """You can never lose with a good enough excuse.""",
]

app = Flask(__name__)

@app.route("/")
def hello():
    return random.choice(QUOTES)

if __name__ == "__main__":
    app.run()
